name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle Wrapper or Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # പ്രോജക്റ്റിന് ആവശ്യമായ കൃത്യമായ പേരിൽ ഒരു പുതിയ കീസ്റ്റോർ ഫയൽ ഉണ്ടാക്കുന്നു
      - name: Generate Local Keystore File
        run: |
          keytool -genkey -v -keystore debug.keystore -alias debugConfig -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -dname "CN=Android Debug,O=Android,C=US"

      # ഇനി ഒരു എററും ഇല്ലാതെ നോർമൽ ആയി ബിൽഡ് ചെയ്യുന്നു
      - name: Build with Gradle
        run: gradle assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
